/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const get_blueprint_svg: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const get_chunk_blueprint_svg: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const get_chunk_voxel_blueprint_svg: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const get_debug_chunk_json: (a: number, b: number, c: number, d: number) => [number, number];
export const get_debug_region_json: (a: number, b: number, c: number) => [number, number];
export const get_large_voxel_blueprint_svg: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const set_doom_controls: (a: number) => void;
export const set_invert_y: (a: number) => void;
export const set_cpu_lod_cutoff: (a: number) => void;
export const set_cpu_max_draw_distance: (a: number) => void;
export const set_cpu_max_splat_half: (a: number) => void;
export const set_cpu_scale: (a: number) => void;
export const set_mouse_sensitivity: (a: number) => void;
export const set_render_scale: (a: number) => void;
export const set_cpu_shadows: (a: number) => void;
export const start: () => void;
export const worker_generate: (a: number, b: number, c: number, d: number) => [number, number];
export const worker_init: (a: number, b: number, c: number) => void;
export const set_face_weights: (a: number, b: number, c: number, d: number) => void;
export const set_fov: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4a98415c8f04dfea: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h00d81ef20398ee11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h00d81ef20398ee11_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h00d81ef20398ee11_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h00d81ef20398ee11_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h00d81ef20398ee11_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha60c758f5c18d619: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
